"use client";

import { useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  CircleHelp,
  Copy,
  ExternalLink,
  Info,
  LoaderCircle,
} from "lucide-react";
import { ScoreRing } from "@/components/ui/score-ring";
import { ToolError } from "@/components/tools/url-tool-form";
import {
  ADSENSE_GROUPS,
  type AdsenseCheckStatus,
  type AdsenseReadinessCheck,
  type AdsenseReadinessResponse,
  type AdsenseReadinessResult,
} from "@/lib/tools/adsense-readiness-types";
import { cn } from "@/lib/utils";

const PROGRESS_STEPS = [
  "Fetching the site homepage",
  "Checking robots, sitemap, and ads.txt",
  "Finding publisher trust pages",
  "Sampling public content pages",
  "Building the readiness checklist",
] as const;

const statusMeta: Record<
  AdsenseCheckStatus,
  { label: string; className: string; icon: typeof CheckCircle2 }
> = {
  pass: {
    label: "Pass",
    className:
      "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/45 dark:text-emerald-300",
    icon: CheckCircle2,
  },
  fix: {
    label: "Fix",
    className:
      "bg-rose-50 text-rose-700 dark:bg-rose-950/45 dark:text-rose-300",
    icon: AlertTriangle,
  },
  review: {
    label: "Review",
    className:
      "bg-amber-50 text-amber-800 dark:bg-amber-950/45 dark:text-amber-300",
    icon: CircleHelp,
  },
  info: {
    label: "Info",
    className:
      "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300",
    icon: Info,
  },
};

export function AdsenseReadinessForm() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<AdsenseReadinessResponse | null>(null);
  const [copied, setCopied] = useState(false);

  async function onSubmit(event: React.FormEvent) {
    event.preventDefault();
    const value = url.trim();
    if (!value || loading) return;

    setLoading(true);
    setProgress(0);
    setResult(null);
    setCopied(false);
    const timers = [1, 2, 3, 4].map((step, index) =>
      window.setTimeout(() => setProgress(step), [1200, 3000, 5200, 8000][index])
    );

    try {
      const response = await fetch(
        `/api/adsense-readiness?url=${encodeURIComponent(value)}`
      );
      const payload = (await response.json()) as AdsenseReadinessResponse;
      setProgress(PROGRESS_STEPS.length - 1);
      setResult(payload);
    } catch {
      setResult({
        success: false,
        error: "Network error — the readiness check could not finish.",
      });
    } finally {
      timers.forEach((timer) => window.clearTimeout(timer));
      setLoading(false);
    }
  }

  async function copyReport(data: AdsenseReadinessResult) {
    const fixes = data.checks.filter((item) => item.status === "fix");
    const reviews = data.checks.filter((item) => item.status === "review");
    const text = [
      `AdSense readiness pre-check — ${data.domain}`,
      `Score: ${data.score}/100 · ${data.verdict}`,
      `${data.summary.passed} passed · ${data.summary.fixes} fixes · ${data.summary.reviews} owner reviews`,
      "",
      "Priority fixes",
      ...(fixes.length
        ? fixes.map(
            (item, index) =>
              `${index + 1}. ${item.title}\n   ${item.recommendation}\n   Source: ${item.reference.label} — ${item.reference.url}`
          )
        : ["No automated fixes were flagged."]),
      "",
      "Confirm yourself",
      ...reviews.map(
        (item, index) =>
          `${index + 1}. ${item.title}\n   ${item.recommendation}\n   Source: ${item.reference.label} — ${item.reference.url}`
      ),
      "",
      data.note,
      "Generated by TheSeoSoul",
    ].join("\n");

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  return (
    <div className="space-y-6">
      <form
        onSubmit={onSubmit}
        className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4 dark:border-slate-800 dark:bg-slate-900/35 sm:p-5"
      >
        <label
          htmlFor="adsense-readiness-url"
          className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500"
        >
          Website domain
        </label>
        <div className="mt-2 flex flex-col gap-2.5 sm:flex-row">
          <input
            id="adsense-readiness-url"
            type="text"
            value={url}
            onChange={(event) => setUrl(event.target.value)}
            placeholder="example.com or any page on your site"
            className="h-12 min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3.5 text-sm text-slate-900 outline-none ring-teal-700/30 focus:ring-2 dark:border-slate-600 dark:bg-slate-950 dark:text-slate-50"
            required
          />
          <button
            type="submit"
            disabled={loading}
            className="inline-flex h-12 items-center justify-center gap-2 rounded-lg bg-teal-800 px-5 text-sm font-semibold text-white hover:bg-teal-700 disabled:cursor-wait disabled:opacity-70 dark:bg-teal-400 dark:text-slate-950 dark:hover:bg-teal-300"
          >
            {loading ? (
              <LoaderCircle className="h-4 w-4 animate-spin" />
            ) : null}
            {loading ? "Checking site…" : "Check AdSense readiness"}
          </button>
        </div>
        <p className="mt-2 text-xs leading-relaxed text-slate-500">
          We return to the site homepage, inspect public trust files and pages,
          then sample up to five content URLs. No account access is requested.
        </p>
      </form>

      {loading ? <ProgressPanel current={progress} /> : null}

      {result && !result.success ? <ToolError>{result.error}</ToolError> : null}

      {result && result.success ? (
        <ReadinessReport
          result={result}
          copied={copied}
          onCopy={() => copyReport(result)}
        />
      ) : null}
    </div>
  );
}

function ProgressPanel({ current }: { current: number }) {
  return (
    <section
      aria-live="polite"
      aria-busy="true"
      className="overflow-hidden rounded-xl border border-teal-800/20 bg-[#0b1220] text-white"
    >
      <div className="h-1 bg-white/10">
        <div
          className="h-full bg-teal-400 transition-[width] duration-700"
          style={{
            width: `${Math.max(12, ((current + 1) / PROGRESS_STEPS.length) * 100)}%`,
          }}
        />
      </div>
      <div className="grid gap-5 p-5 sm:grid-cols-[auto_1fr] sm:items-center">
        <LoaderCircle className="h-8 w-8 animate-spin text-teal-300" />
        <div>
          <p className="font-display text-lg font-bold">Reading the public site</p>
          <p className="mt-1 text-sm text-slate-400">
            {PROGRESS_STEPS[current]}…
          </p>
          <ol className="mt-3 flex flex-wrap gap-1.5">
            {PROGRESS_STEPS.map((step, index) => (
              <li
                key={step}
                className={cn(
                  "rounded-full border px-2 py-0.5 font-mono text-[8px] uppercase tracking-wider",
                  index < current
                    ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-300"
                    : index === current
                      ? "border-teal-300/35 bg-teal-300/10 text-teal-200"
                      : "border-white/10 text-slate-600"
                )}
              >
                {index < current ? "Done" : index + 1}
              </li>
            ))}
          </ol>
        </div>
      </div>
    </section>
  );
}

function ReadinessReport({
  result,
  copied,
  onCopy,
}: {
  result: AdsenseReadinessResult;
  copied: boolean;
  onCopy: () => void;
}) {
  const fixes = result.checks
    .filter((item) => item.status === "fix")
    .sort((a, b) => impactRank(a.impact) - impactRank(b.impact));

  return (
    <div className="space-y-4">
      <section className="relative overflow-hidden rounded-2xl bg-[#0b1220] p-5 text-white sm:p-6">
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 65% 120% at 100% 0%, rgba(45,212,191,.2), transparent 58%)",
          }}
        />
        <div className="relative grid gap-5 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center">
          <ScoreRing
            score={result.score}
            size="md"
            label={`AdSense readiness score ${result.score} out of 100`}
            className="[&_span]:text-white"
          />
          <div className="min-w-0">
            <p className="font-mono text-[9px] font-semibold uppercase tracking-[0.18em] text-teal-300">
              AdSense readiness · public signals
            </p>
            <h2 className="mt-2 font-display text-2xl font-bold tracking-tight">
              {result.verdict}
            </h2>
            <p className="mt-1 truncate text-sm text-slate-400">
              {result.domain} · {result.sampledPages.length} content pages sampled
            </p>
            <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs">
              <Metric value={result.summary.passed} label="passed" tone="good" />
              <Metric value={result.summary.fixes} label="fixes" tone="bad" />
              <Metric value={result.summary.reviews} label="owner reviews" />
            </div>
          </div>
          <button
            type="button"
            onClick={onCopy}
            className="inline-flex h-9 items-center justify-center gap-1.5 rounded-md border border-white/15 px-3 text-xs font-semibold text-slate-200 hover:border-teal-300/40 hover:text-white"
          >
            <Copy className="h-3.5 w-3.5" />
            {copied ? "Copied" : "Copy report"}
          </button>
        </div>
      </section>

      <p className="rounded-lg border border-amber-300/60 bg-amber-50 px-3 py-2.5 text-xs leading-relaxed text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/25 dark:text-amber-200">
        {result.note}
      </p>

      <section className="rounded-lg border border-slate-200 bg-slate-50/55 px-3 py-2.5 dark:border-slate-800 dark:bg-slate-900/30">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-300">
            Every finding below links to the Google document used to define or
            support that check.
          </p>
          <div className="flex flex-wrap gap-1.5 font-mono text-[8px] uppercase tracking-wider">
            <span className="rounded bg-teal-800/10 px-1.5 py-0.5 text-teal-800 dark:bg-teal-300/10 dark:text-teal-300">
              Direct requirement
            </span>
            <span className="rounded bg-blue-800/10 px-1.5 py-0.5 text-blue-800 dark:bg-blue-300/10 dark:text-blue-300">
              Google guidance
            </span>
            <span className="rounded bg-slate-200 px-1.5 py-0.5 text-slate-600 dark:bg-slate-800 dark:text-slate-300">
              Supporting signal
            </span>
          </div>
        </div>
      </section>

      <section className="rounded-xl border border-slate-200 p-4 dark:border-slate-800">
        <div className="flex items-end justify-between gap-3">
          <div>
            <p className="font-mono text-[9px] font-semibold uppercase tracking-[0.16em] text-rose-600 dark:text-rose-300">
              Fix before requesting review
            </p>
            <h3 className="mt-1 font-display text-lg font-bold text-slate-900 dark:text-white">
              {fixes.length
                ? `${fixes.length} public signal${fixes.length === 1 ? "" : "s"} need work`
                : "No automated fixes found"}
            </h3>
          </div>
        </div>
        {fixes.length ? (
          <ol className="mt-3 divide-y divide-slate-200 dark:divide-slate-800">
            {fixes.map((item, index) => (
              <li
                key={item.id}
                className="grid gap-2 py-3 first:pt-0 last:pb-0 sm:grid-cols-[1.5rem_minmax(0,1fr)]"
              >
                <span className="font-display text-sm font-bold text-rose-600 dark:text-rose-300">
                  {index + 1}
                </span>
                <div>
                  <p className="text-sm font-bold text-slate-900 dark:text-white">
                    {item.title}
                  </p>
                  <p className="mt-0.5 text-xs leading-relaxed text-slate-500">
                    {item.evidence}
                  </p>
                  <p className="mt-1 text-xs font-medium leading-relaxed text-slate-700 dark:text-slate-300">
                    {item.recommendation}
                  </p>
                  <FindingReference check={item} />
                </div>
              </li>
            ))}
          </ol>
        ) : (
          <p className="mt-2 text-sm text-emerald-700 dark:text-emerald-300">
            Continue with the owner-only policy and account checks below.
          </p>
        )}
      </section>

      <div className="grid gap-3 lg:grid-cols-2">
        {ADSENSE_GROUPS.map((group) => {
          const checks = result.checks.filter((item) => item.group === group.id);
          return (
            <CheckGroup
              key={group.id}
              title={group.label}
              description={group.description}
              checks={checks}
            />
          );
        })}
      </div>

      <div className="grid gap-3 lg:grid-cols-2">
        <section className="rounded-xl border border-slate-200 p-4 dark:border-slate-800">
          <h3 className="font-display text-base font-bold text-slate-900 dark:text-white">
            Trust pages found
          </h3>
          <ul className="mt-3 divide-y divide-slate-200 dark:divide-slate-800">
            {result.trustPages.map((page) => (
              <li
                key={page.kind}
                className="flex items-center justify-between gap-3 py-2 first:pt-0 last:pb-0"
              >
                <span className="text-sm text-slate-700 dark:text-slate-300">
                  {page.label}
                </span>
                {page.url ? (
                  <a
                    href={page.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1 text-xs font-semibold text-teal-700 hover:underline dark:text-teal-300"
                  >
                    Found
                    <ExternalLink className="h-3 w-3" />
                  </a>
                ) : (
                  <span className="text-xs font-semibold text-rose-600 dark:text-rose-300">
                    Not found
                  </span>
                )}
              </li>
            ))}
          </ul>
        </section>

        <section className="rounded-xl border border-slate-200 p-4 dark:border-slate-800">
          <h3 className="font-display text-base font-bold text-slate-900 dark:text-white">
            Content sample
          </h3>
          {result.sampledPages.length ? (
            <ul className="mt-3 divide-y divide-slate-200 dark:divide-slate-800">
              {result.sampledPages.map((page) => (
                <li key={page.url} className="py-2 first:pt-0 last:pb-0">
                  <div className="flex items-baseline justify-between gap-3">
                    <a
                      href={page.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="min-w-0 truncate text-xs font-semibold text-slate-800 hover:text-teal-700 dark:text-slate-200 dark:hover:text-teal-300"
                    >
                      {page.title}
                    </a>
                    <span className="shrink-0 font-mono text-[9px] text-slate-500">
                      ~{page.words} words
                    </span>
                  </div>
                  <p className="mt-0.5 truncate font-mono text-[9px] text-slate-400">
                    {new URL(page.url).pathname}
                  </p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="mt-2 text-sm text-slate-500">
              No eligible content pages could be sampled.
            </p>
          )}
        </section>
      </div>
    </div>
  );
}

function CheckGroup({
  title,
  description,
  checks,
}: {
  title: string;
  description: string;
  checks: AdsenseReadinessCheck[];
}) {
  return (
    <section className="rounded-xl border border-slate-200 p-4 dark:border-slate-800">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="font-display text-base font-bold text-slate-900 dark:text-white">
            {title}
          </h3>
          <p className="mt-0.5 text-[11px] text-slate-500">{description}</p>
        </div>
        <span className="font-mono text-[9px] text-slate-400">
          {checks.filter((item) => item.status === "pass").length}/{checks.length}
        </span>
      </div>
      <ul className="mt-3 divide-y divide-slate-200 dark:divide-slate-800">
        {checks.map((item) => (
          <CheckRow key={item.id} check={item} />
        ))}
      </ul>
    </section>
  );
}

function CheckRow({ check: item }: { check: AdsenseReadinessCheck }) {
  const meta = statusMeta[item.status];
  const Icon = meta.icon;
  return (
    <li className="py-2.5 first:pt-0 last:pb-0">
      <div className="flex items-start gap-2.5">
        <span
          className={cn(
            "mt-0.5 inline-flex shrink-0 items-center gap-1 rounded px-1.5 py-0.5 font-mono text-[8px] font-semibold uppercase tracking-wider",
            meta.className
          )}
        >
          <Icon className="h-2.5 w-2.5" />
          {meta.label}
        </span>
        <div className="min-w-0">
          <p className="text-xs font-semibold text-slate-900 dark:text-white">
            {item.title}
          </p>
          <p className="mt-0.5 text-[11px] leading-relaxed text-slate-500">
            {item.evidence}
          </p>
          <FindingReference check={item} />
        </div>
      </div>
    </li>
  );
}

function FindingReference({ check }: { check: AdsenseReadinessCheck }) {
  return (
    <a
      href={check.reference.url}
      target="_blank"
      rel="noopener noreferrer"
      className="mt-1.5 inline-flex items-center gap-1 font-mono text-[9px] font-semibold text-teal-700 hover:underline dark:text-teal-300"
    >
      <span className="text-slate-400">{check.reference.relation} ·</span>
      {check.reference.label}
      <ExternalLink className="h-2.5 w-2.5 shrink-0" />
    </a>
  );
}

function Metric({
  value,
  label,
  tone,
}: {
  value: number;
  label: string;
  tone?: "good" | "bad";
}) {
  return (
    <p
      className={cn(
        "text-slate-400",
        tone === "good" && "text-emerald-300",
        tone === "bad" && value > 0 && "text-rose-300"
      )}
    >
      <span className="font-bold tabular-nums text-current">{value}</span>{" "}
      {label}
    </p>
  );
}

function impactRank(impact: AdsenseReadinessCheck["impact"]): number {
  if (impact === "critical") return 0;
  if (impact === "important") return 1;
  return 2;
}
